
model_name: ${module.network.model.model_name}
ema_decay: 0.998
num_classes: null
num_channels: 1
torch_compile: false
pred_emb_dim: ${module.network.model.pred_emb_dim}

model_type: vision
sample_rate: 32000
normalize_waveform: null
normalize_spectrogram: null
length: 5

model:
  _target_: ajepa.modules.models.jepa.JEPA

  model_name: vit_base
  patch_size: 16
  crop_size: [128, 512]          
  pred_depth: 12
  pred_emb_dim: 768
  num_enc_masks: 3
  num_pred_masks: 4
  enc_mask_scale: [0.85, 1.0]
  pred_mask_scale: [0.15, 0.2]
  aspect_ratio: [0.75, 1.5]
  min_keep: 10
  allow_overlap: false
  masking_strategy: multiblock


#checkpoint_path: /workspace/models/ajepa/JEPA_XCM.ckpt                 
                     
